;; skeleton - A project template generated by ahungry-fleece
;; Copyright (C) 2016 Your Name <skeleton@example.com>
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.
;;
;; You should have received a copy of the GNU Affero General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;;; skeleton.lisp

(in-package #:cl-user)

(defpackage skeleton
  (:use :cl)
  (:export :main
           :print-usage))

(in-package #:skeleton)

(defun print-usage ()
  (format t
   "skeleton v/~a.

Usage:

    $ skeleton [-h, --help] # Print this help

"
   (asdf:component-version (asdf:find-system :skeleton))))

(defun main (&rest argv)
  (unless argv
    (setf argv (cdr sb-ext:*posix-argv*)))

  (if (or (equal (first argv) "-h")
          (equal (first argv) "--help"))
      (print-usage)

      (cond
        (t (print-usage)))))

;;; "skeleton" goes here. Hacks and glory await!
