;; skeleton - A project template generated by ahungry-fleece
;; Copyright (C) 2016 Your Name <skeleton@example.com>
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.
;;
;; You should have received a copy of the GNU Affero General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;;; skeleton.lib.stub.lisp

(in-package #:cl-user)

(defpackage skeleton.lib.stub
  (:use :cl)
  (:export
   :echo))

(in-package #:skeleton.lib.stub)

(defun echo (input)
  input)

;;; "skeleton.lib.stub" goes here. Hacks and glory await!
